rules:
  default:
    merge_strategy:
      method: rebase
      rebase_fallback: none
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CodeFactor
          - DCO
          - continuous-integration/travis-ci/pr
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
